### ISSUE TITLE
Update proposal

### ISSUE THREAD

**Issue by ludinov** [RobinTail/merge-sx#177]
Nice lib! Thank you - this saved me a few hours on my initial investigation.
But it looks like I found an easier trick:
```ts
import { Theme } from "@mui/system";
import { SxProps } from "@mui/material";

export const mergeSx = <T extends Theme>(...styles: (SxProps<T> | false | undefined)[]): SxProps<T> => {
  return styles.flat(2).filter(Boolean) as SxProps<T>;
};

// not sure if Theme actually required:
export const mergeSx2 = (...styles: (SxProps | false | undefined)[]): SxProps => {
  return styles.flat(2).filter(Boolean) as SxProps;
};

// or even without filter if no need to support undefined in arguments
// since SxProps respects boolean in array, and then no need for type casting:
export const mergeSx3 = (...styles: (SxProps | false)[]): SxProps => styles.flat(2);
```

not sure about performance, but should be pretty fast I guess..

I end up using this trick like this:

```tsx
<Box 
  sx={[
    localSx,
    { color: "green" },
    props.sx ?? false,
    !!props.major && { color: "red" },
  ].flat(2)}
>{props.children}</Box>
```

**Comment by RobinTail** [comment]
Thank you @ludinov ,

that's an interesting approach. I will try it.

My concern here is a requirement to polyfill `Array::flat` since it's not supported by older browsers.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#browser_compatibility

**Comment by RobinTail** [comment]
I checked the proposed implementation, @ludinov , in #179 .

It's great. I like its simplicity and neatness.
As you expected, it's fast enough.

```
yarn run v1.22.19
$ node -r @swc-node/register tools/benchmark.ts
┌─────────────────────────┬─────────┬────────┬───────┬───────┐
│         (index)         │   10    │  100   │ 1000  │ 10000 │
├─────────────────────────┼─────────┼────────┼───────┼───────┤
│ Current implementation  │ 4541430 │ 532540 │ 52671 │ 5456  │
│ Featured implementation │ 432906  │ 54324  │ 5692  │  578  │
└─────────────────────────┴─────────┴────────┴───────┴───────┘
Done in 42.84s.
```

However, this approach is one order of magnitude less performant than the current implementation.
And even the current implementation does not look as nice and neat as the proposed one, I'm going to keep it.
I believe it's worth it to have a more performant but less compact solution as a library.

Nevertheless, thank you a lot for the effort and suggestion.
