### ISSUE TITLE
`v1.3.0` reports "Module not found: Default condition should be last one" in Next.js

### ISSUE THREAD

**Issue by mwskwong** [RobinTail/merge-sx#205]
Basically, as the title says, not entirely sure what's going on yet, since all I see is the difference between `1.2.0` and `1.3.0` seems to be updating the dependency only. I will take a look at a bit more details later on.

**Edit:** 
Missed the part where the declaration files are now split. Maybe it is related to it?

**Comment by RobinTail** [comment]
Thank you for informing me, @mwskwong 

They are not split, they are duplicated.
Each bundle (CJS and ESM) has its own declaration file.

Could you please provide more details: which entity is reporting that error?

**Comment by RobinTail** [comment]
I managed to reproduce it with Webpack.

> Module not found: Error: Default condition should be last one

**Comment by RobinTail** [comment]
🚀 The issue fixed in v1.3.1, @mwskwong .
Thank you.
